# Generated by Django 6.0.4 on 2026-04-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_member_date_of_joining_member_deposit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_duration_months',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
    ]
