# Generated by Django 6.0.4 on 2026-04-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_member_membership_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='payment_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
