# Generated by Django 6.0.4 on 2026-04-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_member_payment_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="membership_duration_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
